### ISSUE TITLE
Update doc, old parameter

### ISSUE THREAD

**Issue by mike-sirs** [cillaeslopes/strapi-elastic#1]
Hi, thanks for updating the plugin.

On the [screenshot](https://camo.githubusercontent.com/df1c07b83ff4b82c541ca9886e45da1d3b634819fbaa0af42979b2b51b9c9a75/68747470733a2f2f692e6962622e636f2f32794362626d702f636f6465332e706e67) parameter `setting` should be `settings` since it was changed in the helper.js

```
  settings: {
    validStatus: [200, 201],
    validMethod: ['PUT', 'POST', 'DELETE'],
    fillByResponse: false,
    index_prefix: '',
    index_postfix: '',
    importLimit: 3000,
    removeExistIndexForMigration: false,
  },
 ```

**Comment by cillaeslopes** [comment]
Fixed on v1.0.1
